[tool.poetry]
name = "ooda-gpt"
version = "0.1.0"
description = "An auto-GPT that observes and remembers"
authors = ["Luke Heine, Cyrus Nouroozi"]
license = "BUSL-1.1"
readme = "README.md"
packages = [{include = "ooda_gpt"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
# pydantic = "^1"
langchain = { git = "https://github.com/hwchase17/langchain.git", branch = "master" }

[tool.poetry.group.typing.dependencies]
mypy = "^0.991"
types-pyyaml = "^6.0.12.2"
types-requests = "^2.28.11.5"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
playwright = "^1.28.0"
setuptools = "^67.6.1"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
