[tool.poetry]
name = "ooda-gpt"
version = "0.1.0"
description = "An auto-GPT that observes and remembers"
authors = ["Luke Heine", "Cyrus Nouroozi"]
license = "BUSL-1.1"
readme = "README.md"
packages = [{include = "ooda_gpt"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
pydantic = "^1.10.7"
langchain = { git = "https://github.com/hwchase17/langchain.git", branch = "master" }
aiohttp = "^3.8.4"

[tool.poetry.group.typing.dependencies]
mypy = "^1.2.0"
types-pyyaml = "^6.0.12.9"
types-requests = "^2.28.11.17"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
setuptools = "^67.6.1"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
